CREATE OR REPLACE PROCEDURE CHECK_USER (
    user_email IN VARCHAR2,
    user_password IN VARCHAR2,
    user_id OUT NUMBER,
    user_name OUT VARCHAR2
)
AS
    USER_COUNT NUMBER;
		PASS_COUNT NUMBER;
BEGIN

    SELECT COUNT(*) INTO USER_COUNT FROM STUDENT WHERE EMAIL = user_email;

    IF USER_COUNT > 0 THEN
				
				SELECT  COUNT(*) INTO PASS_COUNT FROM STUDENT WHERE EMAIL = user_email AND PASSWORD = user_password;
				
				IF PASS_COUNT >0 THEN 
        SELECT STUDENT_ID, NAME INTO user_id, user_name FROM STUDENT WHERE EMAIL = user_email AND PASSWORD = user_password;
				END IF;
        IF PASS_COUNT = 0 THEN
            user_id := -2; 
            user_name := NULL; 
        END IF;
    ELSE
        user_id := -1; 
        user_name := NULL; 
    END IF;
END;



CREATE SEQUENCE T_ID_SEQ 
INCREMENT BY 1 
START WITH  1 
MAXVALUE 999999999999999 
NOCYCLE ; 


DECLARE
C_COUNT NUMBER;
BEGIN

SELECT COUNT(*) INTO C_COUNT FROM CART_COURSE_RELATIONSHIP C1 WHERE C1.COURSE_ID= :NEW.COURSE_ID AND 
:NEW.STUDENT_ID =(SELECT STUDENT_ID FROM CART C WHERE C1.CART_ID= C.CART_ID  );
IF C_COUNT >0 THEN 
	DELETE FROM  CART_COURSE_RELATIONSHIP
	WHERE CART_ID =(SELECT CART_ID FROM CART WHERE STUDENT_ID = :NEW.STUDENT_ID) AND COURSE_ID= :NEW.COURSE_ID;
END IF;

END;



CREATE TABLE MODULE (
    MODULE_ID NUMBER PRIMARY KEY,
    MODULE_TITLE VARCHAR2(100) NOT NULL
);


CREATE TABLE COURSE_MODULE_RELATIONSHIP (
    COURSE_ID NUMBER,
    MODULE_ID NUMBER,
    PRIMARY KEY (COURSE_ID, MODULE_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    FOREIGN KEY (MODULE_ID) REFERENCES MODULE(MODULE_ID)
);

CREATE TABLE MODULE_CONTENT_RELATIONSHIP (
    CONTENT_ID NUMBER,
    MODULE_ID NUMBER,
    PRIMARY KEY (CONTENT_ID, MODULE_ID),
    FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT(CONTENT_ID),
    FOREIGN KEY (MODULE_ID) REFERENCES MODULE(MODULE_ID)
);


ALTER TABLE CONTENT DROP COLUMN COURSE_ID;


INSERT INTO MODULE(MODULE_ID,MODULE_TITLE) VALUES(1,'Introduction');


-----------------------------------------------
INSERT INTO MODULE(MODULE_ID,MODULE_TITLE) VALUES(1,'Introduction');


INSERT INTO MODULE(MODULE_ID,MODULE_TITLE) VALUES(2,'Environment Setup');
INSERT INTO MODULE(MODULE_ID,MODULE_TITLE) VALUES(3,'Jupyter Overview');

INSERT INTO MODULE(MODULE_ID,MODULE_TITLE) VALUES(4,'Python Crash Course');
INSERT INTO MODULE(MODULE_ID,MODULE_TITLE) VALUES(5,'Python for Data Analysis-NumPy');
INSERT INTO MODULE(MODULE_ID,MODULE_TITLE) VALUES(6,'Python for Data Analysis-Pandas');
INSERT INTO MODULE(MODULE_ID,MODULE_TITLE) VALUES(7,'Python for Data Analysis-Pandas Exercise');
INSERT INTO MODULE(MODULE_ID,MODULE_TITLE) VALUES(8,'Python for Data Visualization - Matpotlib');

------------------------------------------------

-- Insert content for Module 1: Introduction
INSERT INTO CONTENT (CONTENT_ID, CONTENT_TITLE, CONTENT_TYPE, CONTENT_DESCRIPTION, LINK)
VALUES (1, 'Introduction Video', 'Video', 'Introduction to the course', '/Python.mp4');

-- Insert content for Module 2: Environment Setup
INSERT INTO CONTENT (CONTENT_ID, CONTENT_TITLE, CONTENT_TYPE, CONTENT_DESCRIPTION, LINK)
VALUES (2, 'Environment Setup Video', 'Video', 'Setting up the Python environment', '/Python.mp4');

-- Insert content for Module 3: Jupyter Overview
INSERT INTO CONTENT (CONTENT_ID, CONTENT_TITLE, CONTENT_TYPE, CONTENT_DESCRIPTION, LINK)
VALUES (3, 'Jupyter Overview Video', 'Video', 'Overview of Jupyter Notebooks', '/Python.mp4');

-- Insert content for Module 4: Python Crash Course
INSERT INTO CONTENT (CONTENT_ID, CONTENT_TITLE, CONTENT_TYPE, CONTENT_DESCRIPTION, LINK)
VALUES (4, 'Python Crash Course Video', 'Video', 'Crash course on Python programming', '/Python.mp4');

-- Insert content for Module 5: Python for Data Analysis-NumPy
INSERT INTO CONTENT (CONTENT_ID, CONTENT_TITLE, CONTENT_TYPE, CONTENT_DESCRIPTION, LINK)
VALUES (5, 'NumPy Video', 'Video', 'Introduction to NumPy library', '/Python.mp4');

-- Insert content for Module 6: Python for Data Analysis-Pandas
INSERT INTO CONTENT (CONTENT_ID, CONTENT_TITLE, CONTENT_TYPE, CONTENT_DESCRIPTION, LINK)
VALUES (6, 'Pandas Video', 'Video', 'Introduction to Pandas library', '/Python.mp4');

-- Insert content for Module 7: Python for Data Analysis-Pandas Exercise
INSERT INTO CONTENT (CONTENT_ID, CONTENT_TITLE, CONTENT_TYPE, CONTENT_DESCRIPTION, LINK)
VALUES (7, 'Pandas Exercise Video', 'Video', 'Exercise on using Pandas library', '/Python.mp4');

-- Insert content for Module 8: Python for Data Visualization - Matplotlib
INSERT INTO CONTENT (CONTENT_ID, CONTENT_TITLE, CONTENT_TYPE, CONTENT_DESCRIPTION, LINK)
VALUES (8, 'Matplotlib Video', 'Video', 'Introduction to Matplotlib library', '/Python.mp4');

-----------------------------------------------------------------------
INSERT INTO MODULE_CONTENT_RELATIONSHIP(CONTENT_ID,MODULE_ID) VALUES(1,1);
INSERT INTO MODULE_CONTENT_RELATIONSHIP(CONTENT_ID,MODULE_ID) VALUES(2,2);
INSERT INTO MODULE_CONTENT_RELATIONSHIP(CONTENT_ID,MODULE_ID) VALUES(3,3);
INSERT INTO MODULE_CONTENT_RELATIONSHIP(CONTENT_ID,MODULE_ID) VALUES(4,4);
INSERT INTO MODULE_CONTENT_RELATIONSHIP(CONTENT_ID,MODULE_ID) VALUES(5,5);
INSERT INTO MODULE_CONTENT_RELATIONSHIP(CONTENT_ID,MODULE_ID) VALUES(6,6);
INSERT INTO MODULE_CONTENT_RELATIONSHIP(CONTENT_ID,MODULE_ID) VALUES(7,7);
INSERT INTO MODULE_CONTENT_RELATIONSHIP(CONTENT_ID,MODULE_ID) VALUES(8,8);


-----------------------------------------------------------------------------

INSERT INTO COURSE_MODULE_RELATIONSHIP(COURSE_ID,MODULE_ID) VALUES(7,1);
INSERT INTO COURSE_MODULE_RELATIONSHIP(COURSE_ID,MODULE_ID) VALUES(7,2);
INSERT INTO COURSE_MODULE_RELATIONSHIP(COURSE_ID,MODULE_ID) VALUES(7,3);
INSERT INTO COURSE_MODULE_RELATIONSHIP(COURSE_ID,MODULE_ID) VALUES(7,4);
INSERT INTO COURSE_MODULE_RELATIONSHIP(COURSE_ID,MODULE_ID) VALUES(7,5);
INSERT INTO COURSE_MODULE_RELATIONSHIP(COURSE_ID,MODULE_ID) VALUES(7,6);
INSERT INTO COURSE_MODULE_RELATIONSHIP(COURSE_ID,MODULE_ID) VALUES(7,7);
INSERT INTO COURSE_MODULE_RELATIONSHIP(COURSE_ID,MODULE_ID) VALUES(7,8);
