export default function get_selected_course(course_id) {
    

    return (
        `SELECT DISTINCT C.COURSE_ID,C.COURSE_TITLE,C.COURSE_DESCRIPTION,(SELECT AVG(F2.RATING) FROM FEEDBACK F2 WHERE F.COURSE_ID=F2.COURSE_ID  GROUP BY F2.COURSE_ID)RATING
        FROM COURSE C JOIN FEEDBACK F
        ON (C.COURSE_ID=F.COURSE_ID)
        JOIN STUDENT S ON(F.STUDENT_ID=S.STUDENT_ID)
        WHERE C.COURSE_ID= '${course_id}'`
    )
}
//const get_selected_course=`SELECT DISTINCT C.COURSE_ID,C.COURSE_TITLE,C.COURSE_DESCRIPTION,(SELECT AVG(F2.RATING) FROM FEEDBACK F2 WHERE F.COURSE_ID=F2.COURSE_ID  GROUP BY F2.COURSE_ID)RATING