export default function get_popular_courses() {
    return(
        `SELECT C.COURSE_ID ID, C.COURSE_TITLE COURSE_NAME, C.PRICE PRICE ,ROUND(AVG(F.RATING),1)RATING,(SELECT COUNT(*) FROM TRANSACTION T WHERE T.COURSE_ID =F.COURSE_ID GROUP BY T.COURSE_ID)BUY_COUNT
        FROM FEEDBACK F JOIN  COURSE C 
        ON C.COURSE_ID=F.COURSE_ID
        GROUP BY F.COURSE_ID,C.COURSE_TITLE,C.PRICE,C.COURSE_ID
        ORDER BY AVG(F.RATING) DESC
        FETCH FIRST 10 ROWS ONLY`
    );
}